Update perform_grid_job.yml

diff --git a/.github/workflows/perform_grid_job.yml b/.github/workflows/perform_grid_job.yml
--- a/.github/workflows/perform_grid_job.yml
+++ b/.github/workflows/perform_grid_job.yml
@@ -66,11 +66,11 @@ jobs:
         run: |
           COMMENT="✅ About to launch job"
           
-          curl -s -H "Authorization: token $GITHUB_TOKEN" \
-               -H "Accept: application/vnd.github.v3+json" \
-               -X POST \
-               -d "$(jq -nc --arg body "$COMMENT" '{body: $body}')" \
-               "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"
+          # curl -s -H "Authorization: token $GITHUB_TOKEN" \
+          #      -H "Accept: application/vnd.github.v3+json" \
+          #      -X POST \
+          #      -d "$(jq -nc --arg body "$COMMENT" '{body: $body}')" \
+          #      "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"
              
       
       - name: Submit job
@@ -101,11 +101,11 @@ jobs:
         run: |
           COMMENT="✅ Job launched successfully here ${{ steps.alien_submit.outputs.alien_job_url }}"
           
-          curl -s -H "Authorization: token $GITHUB_TOKEN" \
-               -H "Accept: application/vnd.github.v3+json" \
-               -X POST \
-               -d "$(jq -nc --arg body "$COMMENT" '{body: $body}')" \
-               "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"
+          # curl -s -H "Authorization: token $GITHUB_TOKEN" \
+          #      -H "Accept: application/vnd.github.v3+json" \
+          #      -X POST \
+          #      -d "$(jq -nc --arg body "$COMMENT" '{body: $body}')" \
+          #      "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"
              
       - name: Wait job completion
         id: wait_alien
@@ -128,4 +128,39 @@ jobs:
            done
            exit 1
 
+      - name: Check job success
+        shell: bash
+        run: |
+           # We are now analysing failed/pass sub-jobs
+           # (this is also done in O2DPG grid submit; consider modularizing)
+           source alien_env.env
+           JOB_ID=${{ steps.alien_submit.outputs.alien_job_id }}
+           SUBJOBIDS=()
+           SUBJOBSTATUSES=()
+           while [ "${#SUBJOBIDS[@]}" == "0" ]; do
+             QUERYRESULT=$(ALIENPY_JSON=true alien.py ps -a -m ${MY_JOBID})
+             SUBJOBIDS=($(echo ${QUERYRESULT} | jq -r '.results[].id' | tr '\n' ' '))
+             SUBJOBSTATUSES=($(echo ${QUERYRESULT} | jq -r '.results[].status' | tr '\n' ' '))
+             sleep 1
+           done
            
+           LENGTH="${#SUBJOBIDS[@]}"
+           echo "Have ${LENGTH} subjobs"
+           donecounter=0
+           failcounter=0
+           for splitcounter in `seq 1 ${LENGTH}`; do
+             let jobindex=splitcounter-1
+             THIS_STATUS=${SUBJOBSTATUSES[jobindex]}
+             THIS_JOB=${SUBJOBIDS[jobindex]}
+             if [ "${THIS_STATUS}" == "DONE" ]; then
+               let donecounter=donecounter+1
+             else
+	             let failcounter=failcounter+1
+	           fi
+           
+           done
+           if [[ donecounter > 0 ]]; then 
+             exit 0
+           fi
+           exit 1
+            
